<?php

/**
 * @file
 * Code for the mat_resturants feature.
 */
include_once 'mat_resturants.features.inc';

/**
 * Implements of hook_ctools_plugin_directory().
 */
function mat_resturants_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function mat_resturants_form_resturant_node_form_alter(&$form, &$form_state) {
  $form['actions']['submit']['#submit'][] = '_mat_resturants_redirect_callback';
}

/**
 * Custom redirect callback.
 */
function _mat_resturants_redirect_callback($form, &$form_state) {
  $form_state['redirect'] = '<front>';
}

/**
 * Implements hook_theme().
 */
function mat_resturants_theme() {
  $theme = array(
    'resturants_list' => array(
      'variables' => array('title' => NULL, 'resturantsJson' => NULL),
      'template' => 'resturants_list',
    )
  );

  return $theme;
}

/**
 * Template preprocess resturants_list
 */
function template_preprocess_resturants_list(&$vars) {
  $path = drupal_get_path('module', 'mat_resturants');
  drupal_add_js($path . '/js/angular.min.js', 'file');
  drupal_add_js($path . '/js/angular-touch.min.js', 'file');
  drupal_add_js($path . '/js/angular-sanitize.js', 'file');
  drupal_add_js($path . '/js/fastclick.js', 'file');
  drupal_add_js($path . '/js/angular.min.js.map', 'file');
  drupal_add_js('https://maps.googleapis.com/maps/api/js?key=AIzaSyD6kiVgdA_nkfp2P_wE8sUh35l-yPhpNEs', 'file');
  drupal_add_js($path . '/js/gmaps.js', 'file');
  drupal_add_js($path . '/js/handler.js', 'file');

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'resturant')->propertyCondition('status', 1)->propertyOrderBy('created', 'DESC');
  $result = $query->execute();

  if (isset($result['node'])) {
    $entities_ids = array_keys($result['node']);
  } else {
    return false;
  }

  $resturants = node_load_multiple($entities_ids, array(), FALSE);

  $vars['resturantsJson'] = drupal_json_encode($resturants);
}

/**
 * Implements hook_theme().
 */
function mat_resturants_menu() {

  $items['ajax/resturants'] = array(
    'title' => 'Ajax callback',
    'page callback' => 'mat_resturants_content',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Custom page callback that prints restaurants in json format.
 */
function mat_resturants_content() {

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')->entityCondition('bundle', 'resturant')->propertyCondition('status', 1)->propertyOrderBy('created', 'DESC');
  $result = $query->execute();

  if (isset($result['node'])) {
    $entities_ids = array_keys($result['node']);
  } else {
    return false;
  }

  $resturants = node_load_multiple($entities_ids, array(), FALSE);

  foreach ($resturants as $resturant) {

    $stack = array();

    foreach ($resturant->field_tags[LANGUAGE_NONE] as $key => $value) {
      $stack[] = array(
        'tagID' => $value["tid"],
        'namn' => taxonomy_term_load($value["tid"])->name,
      );
    }

    $resturant->tags = $stack;
  }

  header('content-type: application/json; charset=utf-8');

  echo $_GET['callback'] . '(' . json_encode($resturants) . ')';
}
